### ISSUE TITLE
[sugestion] Run with docker-compose

### ISSUE THREAD

**Issue by Bigua** [DrPsychick/docker-dnsmasq#8]
Hi, i've been using this for a while ( great work btw) but it was running standalone. 
It will be great if I can integrate this in my already running docker-compose services. Any help ? tks

**Comment by DrPsychick** [comment]
Sure, where are you stuck? Or what do you need help with?

**Comment by DrPsychick** [comment]
Hey @Bigua , I guess this is resolved? What was your issue and how did you solve it?
